### ISSUE TITLE
Malware warning

### ISSUE THREAD

**Issue by balazser** [cutbox/CutBox#100]
**Describe the bug**
After restarting my computer I got this message:
![image](https://user-images.githubusercontent.com/20303564/82328533-52da8c80-99e0-11ea-9a8a-4727669f08f9.png)

**To Reproduce**
1. Just booted the computer.

**Expected behavior**
The message should not appear.

**Mac Environment (please complete the following information):**
 - macos version: Macos 10.15.4 (19E287) Catalina
 - CutBox version: CutBox version 1.4.10

**Additional context**

**Comment by bahnfrei** [comment]
I've exactly the same issue. CutBox 1.4.10 worked again on Mojave until i performed the upgrade to Catalina 10.15.4 (19E287) yesterday evening 😭

**Comment by jasonm23** [comment]
Unfortunately this is due to Apple's broken gatekeeping in Catalina.

CutBox will still work ok if you cancel the dialog.

I'd recommend anyone truly concerned about CutBox status as malware to do a thorough code review.

Also to build from source to guarantee safety.

I'm not a member of Apple's developer program so it's not possible to use their notarization process.

However see #94 + Libre Office's experience with notarization. (i.e. there's no guarantee that notarization will remove spurious messages about malware.)

This is a troubling anti-competitive / anti open source / free software maneuver by Apple, which I hope is accidental.

**Comment by jasonm23** [comment]
For reference: https://www.zdnet.com/article/apples-macos-catalina-libreoffice-users-still-get-scary-malware-messages/

**Comment by balazser** [comment]
Thank you for the comments. For me, it pops up continuously. Once. I click cancel it reopens. :-/

**Comment by jasonm23** [comment]
If you look at *System Preferences* > *Security* does it mention CutBox?

Please note I don't update Macos for quite a while after a major version update and have no immediate plans to destabilize my setup by moving to Catalina anytime soon.

**Comment by jasonm23** [comment]
Fastest solution is to install XCode 11.3.1 and build CutBox locally.  It is my preference for users to build their own binaries given the landscape that Apple are setting up.

**Comment by bahnfrei** [comment]
> Thank you for the comments. For me, it pops up continuously. Once. I click cancel it reopens. :-/

same here and it doesn't show up in _System Preferences > Security_... so it can't be approved...

**Comment by bahnfrei** [comment]
checked some other options:

````
sudo spctl --master-disable
````
===> not working

````
sudo spctl --add /Applications/CutBox.app
/Applications/CutBox.app: invalid API object reference
````
===> not working as well

**Comment by jasonm23** [comment]
It is now fairly simple to compile your own **CutBox.app**

Do the following:  Check the README for more info.

```
git clone --recursive git@github.com:cutbox:CutBox
cd CutBox
bin/setup
```

This will show you any requirements to build that you don't have.

```
bin/build_local_app
```

If everything worked out ok, a finder window will open and you can drag **CutBox.app** to **/Applications/**
