### ISSUE TITLE
[Feature] Ignore text from password managers

### ISSUE THREAD

**Issue by elder-cb** [cutbox/CutBox#93]
A very useful feature I like in other apps (Paste2) is the possibility to not store passwords in the history: having the ability of ignoring data from certain apps would be great! :)
For example:
- keychain access
- 1password
- lastpass
etc

The text would still be in the system clipboard (some password managers will actually clean the clipboard after a short time) but should not be stored in cutbox history.

**Comment by jasonm23** [comment]
@elder-cb thanks for the feature suggestion Claudio.

If you have any feedback for the following action items, please let me know.

- [ ] Check on application ID availability when accessing the current clipboard
- [ ] Make a visual interaction sketch of a potential UX/UI (@elder-cb please sign off / provide feedback on this.)
- [ ] implement application code for
    - [ ] identify application when capturing clipboard
    - [ ] manage a blacklist of application identifiers
    - [ ] never store blacklist paste text items in history, but do not wipe them from the active system clipboard (CutBox would do this by default.)
- [ ] implement UI/UX for
    - [ ] User can manage blacklist:

e.g. (security allow apps to control UI)

![Screenshot 2020-05-11 at 11 10 20 AM](https://user-images.githubusercontent.com/71587/81520869-17084d00-9378-11ea-8c59-ffe0182f2dd7.png)

![Screenshot 2020-05-11 at 11 10 29 AM](https://user-images.githubusercontent.com/71587/81520873-1a033d80-9378-11ea-8821-e0357ea71d9e.png)

**Comment by jasonm23** [comment]
Looking at Dittostack which seems to have this feature and a UI distinctly similar to CutBox.

**Comment by jasonm23** [comment]
There's unfortunately no support in macos for reading Application ID from the pasteboard items. Other apps which do this have figured out a workaround / hack to implement it.  I do recommend trying out Dittostack by Euan Mapham which is $2.99 but free to try.

Unfortunately it's closed source (as is Paste2) so the method used to identify the app is secret.  I'd be interested to know if you find the blacklisting is 100% reliable (e.g. copy and immediately cmd tab away from the blacklisted app should be an edge case worth testing.)

If it does seem to be reliable I would consider investigating.

The mechanism that CutBox uses to fetch from the clipboard is a continuous polling loop to monitor the clipboard for new items.  Feasibly It could also check the current top level app window, because it is already granted control of the mac.

**Comment by jasonm23** [comment]
Polling clipboard + current application.

- [ ] The timing problem. - clipboard item lifecycle vs current application.
    - [ ] need to know when the _new_ clipboard item was copy/cut
    - [ ] need to ensure current application is only checked when the clipboard item is "new"

**Comment by jasonm23** [comment]
I won't be adding this.

**Comment by elder-cb** [comment]
Thank you for investigating it: I understand the problem :( 
Would be nice if Apple added proper support for clipboard managers through some dedicated API (protected like the accessibility ones) :(
