### ISSUE TITLE
The application does not open

### ISSUE THREAD

**Issue by gonzalt03** [cutbox/CutBox#95]
The application does not open. No error message. I have already tried to completely remove the application and reinstall it. Without success.

MacOS Mojave - 10.14.6 (18G95)

**Comment by awreccan** [comment]
Same here. Started happening all of a sudden without installing any new Cutbox updates. Cutbox version 1.4.5.
![image](https://user-images.githubusercontent.com/10543509/75306667-b0998580-5884-11ea-87c4-f54aa814f026.png)

**Comment by jasonm23** [comment]
Related to #94

**Comment by gonzalt03** [comment]
I am not sure that it is the same problem. I already encountered the #94 problem several weeks ago.

**Comment by balazser** [comment]
Neither works on my mac. :/ macOS Mojave 10.14.6 (18G95)

**Comment by juusee** [comment]
I am experiencing the same issue. 

MacOS Mojave - 10.14.6

**Comment by uqix** [comment]
Some issue on 10.15.3

**Comment by liorgreenb** [comment]
here too on 10.14.6

**Comment by jasonm23** [comment]
Hi all, thanks to NCOV-19 I finally have time to invest in this issue.

First I'd appreciate your pain on this, I've had CutBox non-functional myself for a few weeks and I miss it.

Now that I've investigated more thoroughly the issue is indeed caused by the code signing features in MacOS changing.

The problem is worsened by some abandoned lib dependencies in CutBox which I'm looking at working around.

I'm in the process of changing the fuzzy string matching dependency (simple)

KeyHolder also throws sdk/syntax issues thanks to the ever shifting sand of Swift... I'll try to post daily updates.

**Comment by nirco950** [comment]
> Hi all, thanks to NCOV-19 I finally have time to invest in this issue.
> 
> First I'd appreciate your pain on this, I've had CutBox non-functional myself for a few weeks and I miss it.
> 
> Now that I've investigated more thoroughly the issue is indeed caused by the code signing features in MacOS changing.
> 
> The problem is worsened by some abandoned lib dependencies in CutBox which I'm looking at working around.
> 
> I'm in the process of changing the fuzzy string matching dependency (simple)
> 
> KeyHolder also throws sdk/syntax issues thanks to the ever shifting sand of Swift... I'll try to post daily updates.
> 
> Without these maintenance updates I can't successfully rebuild CutBox binaries (and sign them)

are there any updates?

**Comment by jasonm23** [comment]
I have a time slice opening up on Friday

**Comment by bahnfrei** [comment]
hello! is there any progress yet? i would like to be able to use this magnificent tool again ;-)

**Comment by jasonm23** [comment]
Unfortunately I am dealing with an imminent redundancy so I'm just running
around with my hair on fire 🔥

Once my family is safely looked after I'll get back on CutBox.

I would recommend trying to build your own executable in the mean time.

**Comment by bahnfrei** [comment]
Oh, damn it. Good luck, mate! Hope there's another chance for you to get back on the safe side as soon as possible. I'll keep my fingers crossed!

**Comment by jasonm23** [comment]
Cheers Boss! Hope so 🙏

**Comment by jasonm23** [comment]
Hi all, some good news.  During my quarantine based job search I managed to slice out time to address the build issues on CutBox.

I'm re-familiarising myself with the build process I put together and have successfully created a running app.

I have a bit of config to do, and should update the doc (and add a setup script!) because my home-brewed CI is all shell scripts and (obviously I guess) hard to unpick and get that larger meaningful view after a year+ of not really looking at it. Note to self and imaginary blog post about making sure I structure everything perfectly and meaningfully at all times!

I am chasing down the bizarre crash bug and added a test case, but no joy on that so far.

I'm focussing on getting a working / signed release out.  Main caveat here is that the Apple Notarisation thing is ONLY available to Developer Program members and I am in a "refuse to comply" kinda mood, so I'll test the release on my other mac and if it doesn't go badly I'll announce a release here and on the silent Gitter Channel. 👍 

Lots of love, thanks for still wanting to use CutBox, I miss it too.  

Hopefully  a release will be out today.

**Comment by jasonm23** [comment]
I'm now testing https://github.com/cutbox/CutBox/releases/tag/1.4.6 - I'd like feedback on user tests from anyone who reads this.

**Comment by jasonm23** [comment]
<img width="698" alt="Screenshot 2020-05-09 at 3 42 43 PM" src="https://user-images.githubusercontent.com/71587/81467534-c7a50e00-920b-11ea-94d1-5caa7e5e4d53.png">

Testing now on ^

**Comment by jasonm23** [comment]
Looking good.  I'll wait for feedback here before taking this out of pre-release.

**Comment by uzadude** [comment]
work for me, thanks!

**Comment by 3ielevin** [comment]
it works!!
Thanks

**Comment by gonzalt03** [comment]
It works for me too (Catalina 10.15.4 (19E287)).
_It is a pleasure to recover the application!_

**Comment by DavidGereb** [comment]
works for me too 10.15.4 (19E287)
thanks, big help

**Comment by nirco950** [comment]
works for me too.
Thanks!!

**Comment by jasonm23** [comment]
Thanks for checking and testing folks that's good news :+1: 

I'll cut a proper release today for auto update and fix up the landing page at https://CutBox.github.io

**Comment by itayco** [comment]
Installed 1.4.8, works on Mojave (10.14.6)
Thank you!!

**Comment by bahnfrei** [comment]
thank you so much 🙏  for making it work again!!! 👏

**Comment by balazser** [comment]
also works on my machine. this is the best tool ever. 🍾 🎆 🥳
