### ISSUE TITLE
Cutbox won't start

### ISSUE THREAD

**Issue by awreccan** [cutbox/CutBox#99]
Happened on v1.4.9 as well as v1.4.10  😟 

![image](https://user-images.githubusercontent.com/10543509/82193972-b73a1500-9928-11ea-9eda-a6cf57909d12.png)

**Comment by jasonm23** [comment]
Thank you for the report @awreccan 

Please clear your history / prefs (back it up first.)

**Comment by jasonm23** [comment]
> Thank you for the report @awreccan
> 
> Please clear your history / prefs (back it up first.)

To do this, when CutBox is closed, remove:

    ~/Library/Preferences/info.ocodo.CutBox.plist

**Comment by jasonm23** [comment]
BTW if it's safe to share the cutbox prefs I can use it for testing your issue.

**Comment by jasonm23** [comment]
This will be closed in 24h if no further information is provided.

**Comment by gonzalt03** [comment]
I confirm that CutBox does not work for me too. Strange that overnight there is nothing left. I completely uninstall the application and a reinstallation does not solve the problem.

**Comment by jasonm23** [comment]
.

> I confirm that CutBox does not work for me too. Strange that overnight there is nothing left. I completely uninstall the application and a reinstallation does not solve the problem.

Does that mean the preferences were also deleted too?

Just removing CutBox.app and re-copying it over again won't affect other files.
- - -

Please provide info, i.e. macos version including build number.

If possible, run Console.app and filter for CutBox (e.g. in system.log)

**Comment by gonzalt03** [comment]
Process:               CutBox [37048]
Path:                  /Applications/CutBox.app/Contents/MacOS/CutBox
Identifier:            info.ocodo.CutBox
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CutBox [37048]
User ID:               501

Date/Time:             2020-05-20 10:29:27.467 +0200
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     4.4 (17P4281)
Anonymous UUID:        4D1BFF04-A76C-88B7-05D1-8BCA7CB8A4F6

Sleep/Wake UUID:       84913E19-93BE-4701-9BAD-46EB1F2C246B

Time Awake Since Boot: 97000 seconds
Time Since Wake:       4500 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000101c23000-0000000101c7b000 [  352K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   @|4                          	0x000000010b43d000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeedfdcc18
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010b43d000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x101c23000 -        0x101c7aff7 +@|4 (0) <5C238577-1104-3E1D-8A48-25CD81272369> @|4
       0x10b43c000 -        0x10b4cdeff +@|4 (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> @|4

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 110858
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1236K resident=0K(0%) swapped_out_or_unallocated=1236K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             292K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         300K        2 
__TEXT                             936K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.5M       13

**Comment by gonzalt03** [comment]
<img width="1390" alt="Capture d’écran 2020-05-20 à 10 37 34" src="https://user-images.githubusercontent.com/11817159/82424772-f336bc80-9a85-11ea-9129-d7ffd6e58d75.png">

**Comment by jasonm23** [comment]
I can resign a new release but it looks like a permanent problem.

My recommendation is to install XCode 11.3.1 and build your own binaries.

**Comment by jasonm23** [comment]
Or try Dittostack.

**Comment by nirco950** [comment]
CutBox does not work for me too
Is it possible to add a fix?

**Comment by jasonm23** [comment]
Recommended reading

https://forums.developer.apple.com/thread/110009

**Comment by jasonm23** [comment]
@nirco950 please read the complete thread, unfortunately there is no further action I can take.

CutBox is not intended to be a paid for app, and I am prepared to invest some of my time in development for it.  Community contributions have also been accepted.

However, I will not support the mandatory notarization process within the scope of CutBox or any other free open source software.  While that mandatory process requires a paid for Developer ID from Apple.

I would hope that Apple provides a standard way to notarize the builds from official repo/binary sources for open source software.

Until then this is a huge overstep on the part of Apple and the only way to prevent modify this direction is for users en masse to show their displeasure.  On Reddit, Hacker news etc.

**Comment by jasonm23** [comment]
See #100

Self compilation is now pretty simple.

**Comment by jasonm23** [comment]
https://github.com/cutbox/CutBox/issues/100#issuecomment-680318138
